
export type BusinessType = 'Retail' | 'Restaurant' | 'Service' | 'E-Commerce' | 'Convenience Store';

export type UserRole = 'merchant' | 'iso' | 'overseer';

export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  // Specific to Merchant
  businessType?: BusinessType;
  // Specific to ISO
  organizationName?: string;
  onboardingComplete: boolean;
  credits: number;
  plan: 'Free' | 'Pro' | 'Enterprise';
}

export type ThemeColor = 'green' | 'blue' | 'purple' | 'orange';

export interface AppSettings {
  revenueGoal: number;
  notifications: boolean;
  theme: 'light' | 'dark' | 'system';
  primaryColor: ThemeColor;
  aiResponseStyle: number; // 0 (Simple) to 100 (Data-Driven)
  proxyEndpoint?: string;
}

export type TransactionCategory = 'Inventory' | 'Utilities' | 'Payroll' | 'Marketing' | 'Software' | 'Rent' | 'Miscellaneous' | 'Uncategorized';

export interface Transaction {
  id: string;
  date: string;
  amount: number;
  status: 'Completed' | 'Pending' | 'Failed';
  customer: string;
  items: string[];
  // Fix: Added 'Apple Pay' and 'Wire' to the union type to support all mock transactions
  method: 'Visa' | 'MasterCard' | 'Amex' | 'Square' | 'Stripe' | 'Cash' | 'Apple Pay' | 'Wire';
  category: TransactionCategory;
}

export interface DailyMetric {
  date: string;
  revenue: number;
  transactions: number;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'alert' | 'success';
  read: boolean;
  timestamp: number;
}

export interface Review {
  id: string;
  author: string;
  rating: number;
  text: string;
  date: string;
  sentiment?: 'Positive' | 'Neutral' | 'Negative';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
  isStreaming?: boolean;
}

export interface CreditLog {
  id: string;
  action: string;
  amount: number;
  timestamp: number;
}

export interface Supplier {
  id: string;
  name: string;
  email: string;
  reorderMethod: 'Email' | 'API';
}

export interface InventoryItem {
  id: string;
  name: string;
  sku: string;
  currentStock: number;
  reorderPoint: number;
  unitCost: number;
  supplierId: string;
  dailyBurnRate: number; // Avg units sold per day
  daysRemaining: number;
  status: 'Good' | 'Low' | 'Critical';
}

export interface Order {
  id: string;
  itemId: string;
  quantity: number;
  status: 'Draft' | 'Sent' | 'Delivered';
  date: number;
}

export interface CardBrandMix {
  visa: number;
  mastercard: number;
  amex: number;
  discover: number;
}

export interface MerchantStatementAnalysis {
  merchantName: string;
  mccCode: string;
  mccDescription: string;
  riskLevel: 'Low' | 'Medium' | 'High';

  // Volume
  dailyVolume: number;
  monthlyVolume: number;
  yearlyVolume: number;

  // Ticket
  avgTicketSize: number;
  txnCount: number;

  // Rate & Interchange
  blendedRate: number; // total effective rate %
  cardBrandMix: CardBrandMix;
  interchangeByBrand: { visa: number; mastercard: number; amex: number; discover: number }; // rate %

  // Processing Method
  swipedPercent: number;
  keyedPercent: number;

  // Payment Type Split
  debitPercent: number;
  creditPercent: number;

  // Profitability
  totalResidual: number;
  supportCost: number;
  netProfit: number;

  // Health
  attritionRisk: 'Low' | 'Medium' | 'High';
  growthPattern: 'Growing' | 'Stable' | 'Shrinking';
  fluctuationRate: number; // % swings month over month
}

export type CapabilityStatus = 'live' | 'roadmap' | 'simulated' | 'ai-generated';
export type AuthMode = 'demo' | 'backend';

export interface ActionPlan {
  id: string;
  title: string;
  ownerRole: 'iso' | 'merchant';
  visibleTo: Array<'iso' | 'merchant'>;
  status: 'todo' | 'in_progress' | 'done';
  createdAt: number;
  updatedAt: number;
}

export interface SmartTask {
  id: string;
  text: string;
  completed: boolean;
  isAutoGenerated?: boolean;
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string;
  note?: string;
  impactDirection: 'up' | 'down' | 'neutral';
  impactPercent: number;
  createdAt: number;
  updatedAt: number;
}

export interface Tenant {
  id: string;
  name: string;
  kind: 'iso' | 'merchant';
  createdAt: string;
}

export interface AuthSession {
  sessionId: string;
  userId: string;
  tenantId: string;
  role: UserRole;
  issuedAt: string;
  expiresAt: string;
}

export interface AuthLoginInput {
  email: string;
  password: string;
  mode: AuthMode;
}

export interface AuthLoginResult {
  user: User;
  session: AuthSession;
  mode: AuthMode;
}

export interface ProcessorAccount {
  id: string;
  tenantId: string;
  provider: 'Stripe' | 'Square' | 'Clover' | 'TSYS' | 'Fiserv' | 'Worldpay' | 'Global Payments' | 'Elavon' | 'Payroc';
  status: 'connected' | 'disconnected' | 'error' | 'pending';
  externalAccountId?: string;
  connectedAt?: string;
  lastSyncAt?: string;
}

export interface NormalizedTransaction {
  id: string;
  tenantId: string;
  processorAccountId: string;
  occurredAt: string;
  amount: number;
  currency: string;
  status: 'approved' | 'declined' | 'refunded' | 'voided' | 'pending';
  cardBrand?: 'visa' | 'mastercard' | 'amex' | 'discover' | 'other';
  entryMethod?: 'swiped' | 'chip' | 'contactless' | 'keyed' | 'ecommerce' | 'other';
  merchantId?: string;
  merchantName?: string;
}

export interface PortfolioMetric {
  tenantId: string;
  rangeStart: string;
  rangeEnd: string;
  totalVolume: number;
  transactionCount: number;
  approvedRate: number;
  averageTicket: number;
  sourceStatus: CapabilityStatus;
  generatedAt: string;
}
