import React, { useState, useEffect } from 'react';
import { CheckSquare, Plus, Square, Trash2, Zap } from 'lucide-react';
import { SmartTask, UserRole } from '../types';
import { StorageService } from '../services/storage';

const getSeededTasksByRole = (role: UserRole): SmartTask[] => {
    if (role === 'merchant') {
        return [
            { id: 'm1', text: 'Reorder Arabica Beans (Low Stock)', completed: false, isAutoGenerated: true },
            { id: 'm2', text: 'Review Weekly Sales Report', completed: true, isAutoGenerated: true }
        ];
    }

    if (role === 'iso') {
        return [
            { id: 'i1', text: 'Call "Joe\'s Pizza" (Churn Risk)', completed: false, isAutoGenerated: true },
            { id: 'i2', text: 'Send proposal to "Tech Gadgets"', completed: false, isAutoGenerated: true }
        ];
    }

    return [];
};

interface TodoListProps {
    role: UserRole;
    className?: string;
}

const TodoList: React.FC<TodoListProps> = ({ role, className = '' }) => {
    const [tasks, setTasks] = useState<SmartTask[]>([]);
    const [newTask, setNewTask] = useState('');

    useEffect(() => {
        const existingTasks = StorageService.getSmartTasks(role);

        if (!StorageService.hasSeededSmartTasks(role)) {
            const seededTasks = getSeededTasksByRole(role);
            const dedupedById = new Map<string, SmartTask>();

            [...seededTasks, ...existingTasks].forEach(task => {
                dedupedById.set(task.id, task);
            });

            const mergedTasks = Array.from(dedupedById.values());
            StorageService.saveSmartTasks(role, mergedTasks);
            StorageService.markSmartTasksSeeded(role);
            setTasks(mergedTasks);
            return;
        }

        setTasks(existingTasks);
    }, [role]);

    const updateTasks = (nextTasks: SmartTask[]) => {
        setTasks(nextTasks);
        StorageService.saveSmartTasks(role, nextTasks);
    };

    const addTask = (e: React.FormEvent) => {
        e.preventDefault();
        if (!newTask.trim()) return;
        updateTasks([...tasks, { id: `t_${Date.now()}`, text: newTask.trim(), completed: false }]);
        setNewTask('');
    };

    const toggleTask = (id: string) => {
        updateTasks(tasks.map(t => t.id === id ? { ...t, completed: !t.completed } : t));
    };

    const deleteTask = (id: string) => {
        updateTasks(tasks.filter(t => t.id !== id));
    };

    return (
        <div className={`bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 flex flex-col h-full ${className}`}>
            <div className="p-4 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center">
                <div className="flex items-center gap-2">
                    <div className="p-2 bg-indigo-50 dark:bg-indigo-900/30 rounded-lg">
                        <CheckSquare className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                    </div>
                    <h3 className="font-bold text-gray-900 dark:text-white">Smart Tasks</h3>
                </div>
                <span className="text-xs font-mono text-gray-400">{tasks.filter(t => !t.completed).length} pending</span>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-3">
                {tasks.map(task => (
                    <div key={task.id} className="group flex items-center gap-3 p-2 hover:bg-gray-50 dark:hover:bg-gray-700/30 rounded-lg transition-colors">
                        <button onClick={() => toggleTask(task.id)} className="flex-shrink-0 text-gray-400 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">
                            {task.completed ? <CheckSquare className="w-5 h-5 text-indigo-600 dark:text-indigo-400" /> : <Square className="w-5 h-5" />}
                        </button>
                        <span className={`flex-1 text-sm ${task.completed ? 'text-gray-400 line-through' : 'text-gray-700 dark:text-gray-300'}`}>
                            {task.text}
                        </span>
                        {task.isAutoGenerated && (
                            <Zap className="w-4 h-4 text-amber-400 opacity-0 group-hover:opacity-100 transition-opacity" title="AI Suggested" />
                        )}
                        {!task.isAutoGenerated && (
                            <button onClick={() => deleteTask(task.id)} className="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-red-500 transition-all">
                                <Trash2 className="w-4 h-4" />
                            </button>
                        )}
                    </div>
                ))}
            </div>

            <form onSubmit={addTask} className="p-4 border-t border-gray-100 dark:border-gray-700">
                <div className="flex gap-2">
                    <input
                        type="text"
                        value={newTask}
                        onChange={(e) => setNewTask(e.target.value)}
                        placeholder="Add a task..."
                        className="flex-1 bg-gray-50 dark:bg-gray-900/50 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:text-white placeholder-gray-400"
                    />
                    <button type="submit" className="p-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors">
                        <Plus className="w-5 h-5" />
                    </button>
                </div>
            </form>
        </div>
    );
};

export default TodoList;
