import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const questionsPath = path.join(root, 'planning', 'daily-questions.json');
const logPath = path.join(root, 'PROGRESS_LOG.md');

const raw = fs.readFileSync(questionsPath, 'utf8');
const data = JSON.parse(raw);

const questions = Array.isArray(data.questions) ? data.questions : [];

const done = questions
  .filter((q) => q.status === 'done')
  .sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));

const blocked = questions
  .filter((q) => q.status === 'blocked')
  .sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));

const inProgress = questions
  .filter((q) => q.status === 'in_progress')
  .sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));

const todo = questions
  .filter((q) => q.status === 'todo')
  .sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));

const fmtEvidence = (items = []) =>
  items.length ? items.map((x) => `  - ${x}`).join('\n') : '  - None recorded';

const section = (title, items, formatter) => {
  if (!items.length) return `### ${title}\n- None\n`;
  return `### ${title}\n${items.map(formatter).join('\n')}\n`;
};

const content = `# ONE82 — Daily Progress Log

> This file is auto-generated from \`planning/daily-questions.json\`.
> Do not edit this file manually unless automation is disabled.

## [${data.date}]
- **Phase:** ${data.phase}

${section(
  'Completed',
  done,
  (q) =>
    `- **${q.id}** — ${q.logEntry || q.question}\n  - Completed At: ${q.completedAt || 'Not set'}\n  - Next Step: ${q.nextStep || 'None'}\n  - Evidence:\n${fmtEvidence(q.evidence)}`
)}

${section(
  'In Progress',
  inProgress,
  (q) =>
    `- **${q.id}** — ${q.question}\n  - Next Step: ${q.nextStep || 'None'}\n  - Evidence:\n${fmtEvidence(q.evidence)}`
)}

${section(
  'Blocked',
  blocked,
  (q) =>
    `- **${q.id}** — ${q.question}\n  - Blocker: ${q.blockedReason || 'No blocker detail provided'}\n  - Next Step: ${q.nextStep || 'None'}\n  - Evidence:\n${fmtEvidence(q.evidence)}`
)}

${section(
  'Remaining',
  todo,
  (q) =>
    `- **${q.id}** — ${q.question}\n  - Next Step: ${q.nextStep || 'None'}`
)}
`;

fs.writeFileSync(logPath, content.trim() + '\n');
